---
   name: testing ping of all servers
   hosts: localhost
   tasks:
     - name: ping testing
       ping:


/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.312.b07-1.amzn2.0.2.x86_64

4235410996464cd9a4cbaae0a8b9bc8a
http://ec2-3-110-181-144.ap-south-1.compute.amazonaws.com:8080/

/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.261-2.6.22.2.amzn2.0.2.x86_64/jre/bin/java

jfrog
wget https://bintray.com/jfrog/artifactory-rpms/rpm -O bintray-jfrog-artifactory-rpms.repo
sudo mv bintray-jfrog-artifactory-rpms.repo /etc/yum.repos.d/
sudo yum install jfrog-artifactory-oss
sudha
